### ISSUE TITLE
How to sign EthereumTransaction with Magic?

### ISSUE THREAD

**Issue by ekurutepe** [magiclabs/magic-ios#2]
Can I use `EthereumTransaction.sign(with: EthereumPrivateKey)` to sign a transaction? How do I access the user's private key?

Or should I use `Web3.Eth.sign(from: EthereumAddress, message: EthereumData)` provided by MagicSDK? But it's not clear to me how to convert the signed result data to a `EthereumSignedTransaction` to use with `sendRawTransaction`

Thanks for your help.

**Comment by Ethella** [comment]
@ekurutepe Hi. As a non-custodial solution, Signing is done in the Magic Auth Relayer. 

To interact with the chain, you may call `sendTransaction` with required payloads without worrying about the signing the transaction. 

More detail example can be checked here:
https://github.com/magiclabs/magic-ios-demo/blob/master/Shared-ui/magic-ios-demo/Main/Web3ViewController.swift#L88
