### ISSUE TITLE
Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by EktaAlphait** [magiclabs/magic-ios#3]
- [x] Frame Work react-native

i cloned demo application for magic-ios.  https://github.com/magiclabs/magic-ios-demo.

**Build failed in xcode 13 with the following Error:** 
Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator.

**Here is the screen shot:**

![Screenshot 2022-01-25 at 3 37 55 PM](https://user-images.githubusercontent.com/98520704/151338618-a07a1027-940d-44a1-b75f-b350452ba381.png)

**Comment by Ethella** [comment]
Hey @EktaAlphait. Which package manager did you try? SPM or Cocoapods?
If you use RN with the iOS library, SPM shall work just fine or even you could clone the repo as it's open-source now. 😄

**Comment by EktaAlphait** [comment]
We tried with SPM. We followed all the steps given on the below links :
https://magic.link/docs/login-methods/email/integration/ios
https://github.com/magiclabs/magic-ios-ext

We also added the package dependencies as mentioned but still we are getting the same error

![Screenshot 2022-01-31 at 11 07 27 AM](https://user-images.githubusercontent.com/98520704/151799043-e5495483-f680-40d5-8e7c-90ef435bab83.png)

![Screenshot 2022-01-31 at 11 17 01 AM](https://user-images.githubusercontent.com/98520704/151799066-890e8550-85c8-413e-8ff5-1d0486c0e6f9.png)
![Screenshot 2022-01-31 at 11 25 36 AM](https://user-images.githubusercontent.com/98520704/151799082-7b050d10-ca28-4a58-9e71-1824f197b17c.png)
![Screenshot 2022-01-25 at 3 37 55 PM](https://user-images.githubusercontent.com/98520704/151799094-5ebb3498-b2dd-41ca-bb2e-249e3024ac10.png)

**Comment by Ethella** [comment]
Another possible cause is that you're using M1 chip Mac. If that's the case try open the Xcode in Rosetta and rebuild the project. 

If the error still persists, please lmk.

**Comment by EktaAlphait** [comment]
- [x] Open using Rosetta

**Comment by EktaAlphait** [comment]
- [x] Open using Rosetta

we tried above solution, Open using Rosetta is solved BigInt issue. But we are getting **"Pods/RCT-Folly/folly/container/detail/F14Table.cpp:41:10: Thread-local storage is not supported for the current target"**.

**Comment by EktaAlphait** [comment]
We are able to solve above issue and build app successfully. But we are getting another error when we enter email and submit.

**"Error: Magic SDK Error: [MODAL_NOT_READY] Modal is not ready"**.

![Screenshot 2022-02-01 at 4 16 55 PM](https://user-images.githubusercontent.com/98520704/151957030-deb67b50-344b-4fc1-b3e5-5667b33c0559.png)


  
![Screenshot 2022-02-01 at 4 20 56 PM](https://user-images.githubusercontent.com/98520704/151957041-0632e8ce-6f30-4ab7-aa05-04cea4a1e9e9.png)

**Comment by franzwarning** [comment]
Same issue here

**Comment by Ethella** [comment]
@franzwarning Hi, could you elaborate on which error you're having and in what procedure?

**Comment by Ethella** [comment]
Adding the following line in the Podfile may help to mitigate this issue

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SKIP_INSTALL'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
```
