### ISSUE TITLE
Crash for users setting up new devices (broken keychain)

### ISSUE THREAD

**Issue by tristan-warner-smith** [magiclabs/magic-ios#36]
**Describe the bug**
A minority of users who swap devices, for whom apps using Magic SDK are automatically re-installed restore the keychain content, but do not enable access to it due to biometric signature differences.

This causes the `DPop.swift` line `let signature = try! privateKey.signature(for: signingInputData)` to crash irrecoverably.
In this case `try retrieveKeyFromKeychain` does not `throw`.

I raised a [hopeful PR](https://github.com/magiclabs/magic-ios/pull/35) to patch the symptom but [here's the Apple Forum](https://developer.apple.com/forums/thread/682162?answerId=726099022#726099022) reference that says they're aware of this issue but that you have you handle it yourself.

In the PR I prevent the crash, I'm not sure if this means you'll recreate the token later, or if the key would need to be explicitly removed as mentioned in the Apple Forum post above.

**To Reproduce**
1. Install an app with an active, cached auth credential from the Magic SDK
2. Buy a new device and use restore
3. Attempt to access a login flow that references `Magic.getIdToken`
4. See crash

**Expected behavior**
No crashes, a self-healing recoverable flow 

**Screenshots**
![image](https://github.com/magiclabs/magic-ios/assets/102950712/c98e2be8-d9da-4b97-ac2c-0e5da73342ed)
![image](https://github.com/magiclabs/magic-ios/assets/102950712/de614bca-a400-401d-970f-cf12441290c0)

**Environment**
 - Package Version: 10.0.0
 - XCode Version: 15.2
 - Swift Version: 5.8
 - Simulator / Device OS: Device no OS specificity, os bug seems to have existed for several versions

**Additional context**

**Comment by Ariflo** [comment]
Fixed: https://github.com/magiclabs/magic-ios/pull/35
